### ISSUE TITLE
Can't excute install.sh

### ISSUE THREAD

**Issue by Landaluce** [secdec/adapt#2]
I've tried: `sudo ./install.sh`
and I got: `./install.sh: command not found`
then I tried: `sudo python3 adapt.py `
and I got this error message:
```
It seems that you have not run the installer script.
We will now run that briefly before continuing.
Traceback (most recent call last):
  File "adapt.py", line 37, in <module>
    subprocess.call(["./install.sh"])
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

**Comment by hkjalaan** [comment]
> I've tried: `sudo ./install.sh`
> and I got: `./install.sh: command not found`
> then I tried: `sudo python3 adapt.py `
> and I got this error message:
> 
> ```
> It seems that you have not run the installer script.
> We will now run that briefly before continuing.
> Traceback (most recent call last):
>   File "adapt.py", line 37, in <module>
>     subprocess.call(["./install.sh"])
>   File "/usr/lib/python3.5/subprocess.py", line 557, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> PermissionError: [Errno 13] Permission denied
> ```

hi Landaluce also me i have this problem but i solve it, try to open install.sh and delete if statement 

 if [[ $EUID -eq 0 ]]; then
echo "This script should no longer be run as root"
exit 1
fi
 

and save & run

**Comment by hkjalaan** [comment]
> I've tried: `sudo ./install.sh`
> and I got: `./install.sh: command not found`
> then I tried: `sudo python3 adapt.py `
> and I got this error message:
> 
> ```
> It seems that you have not run the installer script.
> We will now run that briefly before continuing.
> Traceback (most recent call last):
>   File "adapt.py", line 37, in <module>
>     subprocess.call(["./install.sh"])
>   File "/usr/lib/python3.5/subprocess.py", line 557, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> PermissionError: [Errno 13] Permission denied
> ```

![kali linux-2019-01-31-10-59-27](https://user-images.githubusercontent.com/27056823/52037178-b3be2700-2547-11e9-9861-062f89357a6c.png)

**Comment by hkjalaan** [comment]
hi secdec how i can this?????
![kali linux-2019-01-31-11-03-52](https://user-images.githubusercontent.com/27056823/52037324-1e6f6280-2548-11e9-88f6-4b326bcb1e55.png)

**Comment by matthewD-AVI** [comment]
Hello, I just want to make sure that I am clear with the situation. You have now been able to run the install script but are having trouble with a JSONDecoder while executing the actual tests scripts specifically the crypst_001 test correct?

**Comment by Landaluce** [comment]
I've tried what hkjalaan suggested,  but I still can't get install.sh to work

**Comment by matthewD-AVI** [comment]
I have so far been unable to reproduce Landaluce's issue but I will continue to try so that I may assist

**Comment by matthewD-AVI** [comment]
@Landaluce can you ensure that install.sh has execute as part of its permission. I was able to reproduce the exact same errors as you when it does not.

`sudo chmod +x install.sh` should fix this problem

then run install.sh without sudo

![image](https://user-images.githubusercontent.com/35819157/52581042-b21e1a00-2df7-11e9-9f06-e9f46b5bd451.png)

**Comment by matthewD-AVI** [comment]
I made a commit that should resolve these issues involving the install script. I am also updating the wiki to mention checking the executable properties of install.sh script. If there are further problems please open a separate issue and I will work on them promptly.

**Comment by Landaluce** [comment]
> @Landaluce can you ensure that install.sh has execute as part of its permission. I was able to reproduce the exact same errors as you when it does not.
> 
> `sudo chmod +x install.sh` should fix this problem
> 
> then run install.sh without sudo
> 
> ![image](https://user-images.githubusercontent.com/35819157/52581042-b21e1a00-2df7-11e9-9f06-e9f46b5bd451.png)

Thank you @matthewD-AVI, this worked for me.

**Comment by sdancer75** [comment]
Check the case that the script file "install.sh" was created in windows format. Rewrite the script under vi or use the "dos2unix" converter.

https://waterlan.home.xs4all.nl/dos2unix.html
https://stackoverflow.com/questions/14219092/bash-script-and-bin-bashm-bad-interpreter-no-such-file-or-directory
