### ISSUE TITLE
install missing components

### ISSUE THREAD

**Issue by fuzzy17** [secdec/adapt#3]
I downloaded "master.zip" as there is nothing in releases.  So, Centos 7:

Installing for Linux: 
Please do not press anything until the script is finished, go take a break
sudo apt-get update -y: DONE
sudo apt-get install python3-pip -y: DONE
sudo apt-get install python3-scipy -y: DONE
sudo apt-get install default-jre -y: DONE
sudo apt-get install nmap -y: DONE
sudo apt-get install docker.io -y: DONE
sudo apt-get install git -y: DONE
Checking for zap: FOUND
Checking for wig: NOT FOUND
Installing wig: ./install.sh: line 104: cd: wig: No such file or directory
python3: can't open file 'setup.py': [Errno 2] No such file or directory
FAILED

DONE
/home/auser
Checking paramiko: ./install.sh: line 119: cd: lib: No such file or directory
NOT FOUND
Installing paramiko dev: ./install.sh: line 125: cd: paramiko: No such file or directory
python3: can't open file 'setup.py': [Errno 2] No such file or directory
FAILED

DONE
/home/auser/adapt-master
Checking testssl: ./install.sh: line 140: cd: lib: No such file or directory
NOT FOUND
Installing testssl dev: DONE
Checking for SecLists: ./install.sh: line 153: cd: var: No such file or directory
NOT FOUND
Installing SecLists: ./install.sh: line 158: git: command not found
DONE
mkdir: cannot create directory ‘output’: Permission denied
sudo pip3 install --user python-nmap: DONE
sudo pip3 install --user python-owasp-zap-v2.4: DONE
sudo pip3 install --user beautifulsoup4: DONE
sudo pip3 install --user lxml: DONE
sudo pip3 install --user dicttoxml: DONE
sudo pip3 install --user progressbar2: DONE
sudo pip3 install --user pathlib: DONE
sudo pip3 install --user bcrypt: DONE
sudo pip3 install --user pynacl: DONE
touch: cannot touch './var/adapt_installed': Permission denied
ADAPT install: FINISHED

**Comment by matthewD-AVI** [comment]
ADAPTs a file verifying that the install process has been run. It seems that this file is unable to be created due to permission, I will look into this right away

**Comment by matthewD-AVI** [comment]
I made a commit that should fix your issue, will now sudo touch to create the validation file.
