### ISSUE TITLE
Problems with installer.sh

### ISSUE THREAD

**Issue by xpelican** [secdec/adapt#5]
Hello, and first of all, thank you for undertaking this project - It's a nice idea which I expect will be quite valuable in security testing.

I had a few problems during the install that I guess would be pretty easy for you to fix. You can see the relevant output lines from installer.sh below:

`Checking paramiko: NOT FOUND`
`Installing paramiko dev: ./install.sh: line 125: cd: paramiko: No such file or directory`
`python3: can't open file 'setup.py': [Errno 2] No such file or directory`
`FAILED`

`Checking testssl: ./install.sh: line 140: cd: lib: No such file or directory`
`NOT FOUND`

`Installing SecLists: fatal: could not create work tree dir 'SecLists': Permission denied`

`mkdir: cannot create directory ‘output’: Permission denied`

The system I ran this on was Ubuntu 18.04 64-bit.

I'm now going to edit the installer script to hopefully fix these issues without breaking anything. I'll let you know how it goes!

**Comment by xpelican** [comment]
Okay, so the problems seem to stem from a git clone command to rely on superuser permissions to function on my system.

The reason it couldn't find the lib directory afterwards was due to the script trying to go back to the previous directory with "cd -" _as part of the successful outcome_ of the if condition.

I recommend two fixes that would make things much easier and more compatible for you:
1. Obviously, place the cd commands outside of conditionals,
2. Use absolute paths instead of relative paths in your cd commands. One good way to do this is to specify the variable "$launch_directory" at the start of your script as output from the "pwd" command and then specify the paths afterwards as things like "$launch_directory"/lib

**Comment by matthewD-AVI** [comment]
Thank you for your insight. If you would like to implement these changes please feel free to make a pull request for review.

**Comment by xpelican** [comment]
Will do, and thank you for your prompt reply!

I've fixed the installer at this point to implement the changes I've mentioned, and it works. I'm now having a different error running the main python script however, and will post about that in another issue.

**Comment by xpelican** [comment]
I've created a merge request with the fixed installer.sh, you may close this issue.

**Comment by matthewD-AVI** [comment]
Thank you for the pull request. It is now merged and I will be closing this issue
