### ISSUE TITLE
Internal Error from Zap

### ISSUE THREAD

**Issue by xpelican** [secdec/adapt#6]
When trying to execute "python3 adapt.py", the program exists with the following error message:

`failed during test_logins. Expected zap message, got: internal_error`

Is this an error you recognize?  In previous output, zap seems to initialize properly, so I have no idea what could be going wrong.

Here's the entire output for completeness' sake:

```
'adapt_main [INFO] : Loading config file'
'adapt_main [INFO] : Checking command line args'
'adapt_main [INFO] : Final config setup...'
Valid service username:
Valid service password:
'adapt_main [INFO] : ... Done'
'adapt_main [INFO] : Test bed setup starting...'
'adapt_main [INFO] : Test bed setup done'
'adapt_main [INFO] : http://localhost:8080'
'adapt_main [INFO] : Initializing zap'
'zap_interface [INFO] : open zap daemon /opt/ZAP_2.7.0/zap.sh'
'zap_interface [INFO] : Waiting for zap startup... '
[==============================================================================================] 100%
'zap_interface [INFO] : DONE'
'zap_interface [INFO] : Connecting to zap... '
'zap_interface [INFO] : Opening url'
'zap_interface [INFO] : Excluded path: /logout.php'
'zap_interface [INFO] : Excluded path: /logout'
/opt/adapt/login_format.py:88: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 88 of the file /opt/adapt/login_format.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  s = soup(dvwa_get.text)
'zap_interface [INFO] : Authentication failed: list index out of range'
'zap_interface [INFO] : Finished setup'
'adapt_main [INFO] : Zap initialized'
'adapt_main [INFO] : Checking for authorization availability...'
'adapt_main [INFO] : Zap spider starting...'
'zap_interface [INFO] : Spider start'
'zap_interface [INFO] : ADAPT Context'
'zap_interface [INFO] : scanid: 0'
[==============================================================================================] 100%
'zap_interface [INFO] : Spider done'
'adapt_main [INFO] : DONE'
'adapt_main [INFO] : Zap pscan starting... '
'zap_interface [INFO] : Pscan start'
'zap_interface [INFO] : This could take a while. Please be patient.'
[==============================================================================================] 100%
'zap_interface [INFO] : Pscan done'
'adapt_main [INFO] : DONE'
'adapt_main [INFO] : Zap ascan starting...'
'zap_interface [INFO] : Ascan start'
[==============================================================================================] 100%
'zap_interface [INFO] : Ascan done'
'adapt_main [INFO] : DONE'
'adapt_main [INFO] : Pulling results from zap'
'adapt_main [INFO] : Initializing owasp suite'
'owasp_suite [INFO] : Finished setup'
'adapt_main [INFO] : Owasp initialized'
'adapt_main [INFO] : Running suite'
'owasp_suite [INFO] : Nmap Starting'
'owasp_suite [INFO] : Nmap finished'
'owasp_suite [INFO] : Owasp starting'
'owasp_suite [INFO] : Invoking test: config_002...'
'owasp_suite [INFO] : Invoking test: crypst_001...'
'owasp_suite [INFO] : Invoking test: crypst_002...'
'owasp_suite [INFO] : Invoking test: err_001...'
'owasp_suite [INFO] : Invoking test: err_002...'
[=                                                                                             ] 100%
'owasp_suite [INFO] : Invoking test: info_002...'
'owasp_suite [INFO] : Invoking test: inpval_001...'
'owasp_suite [INFO] : Invoking test: inpval_002...'
'owasp_suite [INFO] : Invoking test: inpval_003...'
Traceback (most recent call last):
  File "adapt.py", line 318, in <module>
    main()
  File "adapt.py", line 303, in main
    pentester.run()
  File "adapt.py", line 71, in run
    return self.start_penetration_testing()
  File "adapt.py", line 132, in start_penetration_testing
    self.owasp_results = owasp.run()
  File "/opt/adapt/src/owasp_suite.py", line 134, in run
    int_res = internal()
  File "/opt/adapt/src/owasp_suite.py", line 452, in inpval_003
    resp = self.zap.send_request( req )
  File "/opt/adapt/src/zap_interface.py", line 95, in send_request
    raise Exception("Request {} failed during test_logins. Expected zap message, got: {}".format(request, resp))
Exception: Request PUT http://localhost:8080/ HTTP/1.0

 failed during test_logins. Expected zap message, got: internal_error
```

**Comment by matthewD-AVI** [comment]
I have never come across this error myself, It may be related to not having proper authentication. If you have an authentication script I would recommend trying with that. I would also like to confirm the test following inpval_003 are working. Can you disable that specific test and run again

**Comment by xpelican** [comment]
Okay, I think I'm doing two things wrong here.

1. I might have put in invalid credentials when it asked me for "Valid service username" and "Valid service password". Can you specify what the username/password is for here - as I simply tried with some made up test names like "usertest" and "passwordtest", so that might be the cause for an authentication error right there.

2. What's the way to disable inpval_003 from running? I tried removing it from the list specifying "test_methods" in line 126, but that didn't seem to change anything, got the same error.

**Comment by xpelican** [comment]
Okay, I figured out how to disable the inpval_003 test (for reference to others, by editing the **adapt.config** file and under `[OWASP_OPTIONS]`, changing `inpval_003 = on` to `off`

And now, adapt.py runs without an errors and exits with `'adapt_main [INFO] : Test bed finished' `

However, during the zap startup stage, I'm still getting authentication errors:
```
('zap_interface [INFO] : Authentication failed: '
 "HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with "
 'url: /login.php (Caused by '
 "NewConnectionError('<urllib3.connection.HTTPConnection object at "
 '0x7f03359d8240>: Failed to establish a new connection: [Errno 111] '
 "Connection refused',))")
```

Not sure how to move forward from here, as I'm not familiar with how OWASP ZAP works.

Also, it would be better for your program's usability if you could provide more detailed steps on how to run it in your **README.md**.

For instance, before running the program successfully and seeing it exit without actually doing anything or giving me any further prompts to do anything, I had _no idea_ I had to specify certain flags (like --target, --risk etc.) when running it - I only realized the existence of these after seeing it not do anything and reviewing the code to see where I went wrong.

So, two steps that could really benefit your project would be:
- Providing a list of the options, along with at least somewhat detailed examples on how to use them,
- Step-by-step instructions detailing an example run
- Recommending users a vulnerable web app (such as Damn Vulnerable Web App: https://github.com/ethicalhack3r/DVWA) to demonstrate the program's capabilities

Once again, thank you for undertaking this project, I expect I'll be using it quite often once I manage to get it running :)

**Comment by matthewD-AVI** [comment]
You should not have to use the run time flags if you edit the configuration file to point at a specific target etc. Also as far as authentication goes it is up to the user to write their own authentication script. There is some guidance here https://github.com/secdec/adapt/wiki/Authentication but since every application handles authentication differently it is still up to the user. Configuration help is also available on the wiki here https://github.com/secdec/adapt/wiki/Configuration. Thank you for all your input and I hope you find ADAPT useful
