### ISSUE TITLE
Error in execution (Novice User)

### ISSUE THREAD

**Issue by Sydwicked** [secdec/adapt#8]
Please help me

Warning: Nashorn engine is planned to be removed from a future JDK release
Warning: Nashorn engine is planned to be removed from a future JDK release
'zap_interface [INFO] : DONE'
'zap_interface [INFO] : Connecting to zap... '
'zap_interface [INFO] : Opening url'
'zap_interface [INFO] : Excluded path: /logout.php'
'zap_interface [INFO] : Excluded path: /logout'
('zap_interface [INFO] : Authentication failed: '
 "HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with "
 'url: /login.php (Caused by '
 "NewConnectionError('<urllib3.connection.HTTPConnection object at "
 '0x7f39dacac510>: Failed to establish a new connection: [Errno 111] '
 "Connection refused'))")
'zap_interface [INFO] : Finished setup'
'adapt_main [INFO] : Zap initialized'
'adapt_main [INFO] : Checking for authorization availability...'
'adapt_main [INFO] : Zap spider starting...'
'zap_interface [INFO] : Spider start'
'zap_interface [INFO] : ADAPT Context'
'zap_interface [INFO] : scanid: url_not_in_context'
recent call last):
  File "adapt.py", line 318, in <module>
    main()
  File "adapt.py", line 303, in main
    pentester.run()
  File "adapt.py", line 71, in run
    return self.start_penetration_testing()
  File "adapt.py", line 94, in start_penetration_testing
    zapper.spider()
  File "/home/xxx/adapt/src/zap_interface.py", line 205, in spider
    scan_progress = int(self.zap.spider.status(scanid))
ValueError: invalid literal for int() with base 10: 'does_not_exist'

**Comment by matthewD-AVI** [comment]
Hello this is an error I have not seen before. In order to investigate I would like some extra information. What is the language of the web application you are running against? What operating system are you running. Did you have zap installed on your machine before running install.py? Did you run install.py?

**Comment by matthewD-AVI** [comment]
I am closing this issue due to lack of response and information needed to diagnose the issue. Please feel free to reach out again.

**Comment by marevalo10** [comment]
I have a similar problem. Application is in .netcore on a Windows Server 2016. I'm running it in a Kali Linux, including the Zap. BTW the installer also installed it again.
I modified the adapt.config to:
....
target = https://www.mywebpage.com/app
context = http://localhost:8080
....

I'm not sure if this is ok or not. 
My error is:
("zap_interface [INFO] : Authentication failed: 'str' object has no attribute "
 "'items'")
'zap_interface [INFO] : Finished setup'
'adapt_main [INFO] : Zap initialized'
'adapt_main [INFO] : Checking for authorization availability...'
'adapt_main [INFO] : Zap spider starting...'
'zap_interface [INFO] : Spider start'
'zap_interface [INFO] : ADAPT Context'
'zap_interface [INFO] : scanid: url_not_in_context'
[                                                                                              ] N/A%Traceback (most recent call last):
  File "./adapt.py", line 318, in <module>
    main()
  File "./adapt.py", line 303, in main
    pentester.run()
  File "./adapt.py", line 71, in run
    return self.start_penetration_testing()
  File "./adapt.py", line 94, in start_penetration_testing
    zapper.spider()
  File "/home/marevalo/pentest/adapt/src/zap_interface.py", line 205, in spider
    scan_progress = int(self.zap.spider.status(scanid))
ValueError: invalid literal for int() with base 10: 'does_not_exist'
